inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 90

Style/NumberedParametersLimit:
  Max: 3  

Style/ParallelAssignment:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
    Enabled: false
